"""init

Revision ID: 8aea1c740dcd
Revises: 
Create Date: 2020-07-10 10:24:48.413746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8aea1c740dcd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('multi_sensor_reading',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sensor1', sa.Float(), nullable=True),
    sa.Column('sensor2', sa.Float(), nullable=True),
    sa.Column('sensor3', sa.Float(), nullable=True),
    sa.Column('sensor4', sa.Float(), nullable=True),
    sa.Column('sensor5', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('particleid', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_multi_sensor_reading_timestamp'), 'multi_sensor_reading', ['timestamp'], unique=False)
    op.create_table('temperature_reading',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('particleid', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_temperature_reading_timestamp'), 'temperature_reading', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_temperature_reading_timestamp'), table_name='temperature_reading')
    op.drop_table('temperature_reading')
    op.drop_index(op.f('ix_multi_sensor_reading_timestamp'), table_name='multi_sensor_reading')
    op.drop_table('multi_sensor_reading')
    # ### end Alembic commands ###
